# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./hack/make/completions
builds:
  - id: darwin
    main: ./cmd/disass
    binary: disass
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
  - id: ios
    main: ./cmd/disass
    binary: disass
    env:
      - CGO_ENABLED=1
      - CC=$GOROOT/misc/ios/clangwrap.sh
    goos:
      - ios
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    hooks:
      post: ./hack/make/codesign {{ .Path }}
  # - id: linux
  #   main: ./cmd/disass
  #   binary: disass
  #   env:
  #     - CGO_ENABLED=1
  #   goos:
  #     - linux
  #   goarch:
  #     - amd64
  # - id: windows
  #   main: ./cmd/disass
  #   binary: disass
  #   env:
  #     - CGO_ENABLED=1
  #   goos:
  #     - windows
  #   goarch:
  #     - amd64
universal_binaries:
  - id: darwin
    replace: true
    name_template: "disass"
archives:
  - id: default_archive
    name_template: "disass_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - completions/*
checksum:
  name_template: "checksums.darwin.txt"
  disable: false
signs:
  - artifacts: checksum
snapshot:
  version_template: "{{ incpatch .Version }}-next"
brews:
  - name: disass
    repository:
      owner: blacktop
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/blacktop/arm64-cgo"
    description: "MachO ARMv9-a Disassembler"
    dependencies:
      - name: bat
        type: optional
    install: |
      bin.install "disass"
      bash_completion.install "completions/_bash" => "disass"
      zsh_completion.install "completions/_zsh" => "_disass"
      fish_completion.install "completions/_fish" => "disass.fish"
    test: |
      system "#{bin}/disass --version"
changelog:
  sort: asc
  use: github
  groups:
    - title: Dependency updates
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge branch
release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/blacktop/arm64-cgo/compare/{{ .PreviousTag }}...{{ .Tag }}
    ## What to do next?
    - Follow us on [Twitter](https://twitter.com/blacktop__);
    - Follow us on [Mastodon](https://mastodon.social/@blacktop)
