# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./hack/make/completions
builds:
  - id: darwin
    main: ./cmd/disass
    binary: disass
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  # - id: linux
  #   main: ./cmd/disass
  #   binary: disass
  #   env:
  #     - CGO_ENABLED=1
  #   goos:
  #     - linux
  #   goarch:
  #     - amd64
  # - id: windows
  #   main: ./cmd/disass
  #   binary: disass
  #   env:
  #     - CGO_ENABLED=1
  #   goos:
  #     - windows
  #   goarch:
  #     - amd64
universal_binaries:
  - id: darwin
    replace: true
    name_template: "disass"
archives:
  - replacements:
      darwin: macOS
      amd64: x86_64
      all: universal
    name_template: "disass_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - completions/*
checksum:
  name_template: "checksums.darwin.txt"
  disable: false
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: disass
    tap:
      owner: blacktop
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/blacktop/arm64-cgo"
    description: "MachO ARMv9-a Disassembler"
    dependencies:
      - name: bat
        type: optional
    install: |
      bin.install "disass"
      bash_completion.install "completions/_bash" => "disass"
      zsh_completion.install "completions/_zsh" => "_disass"
      fish_completion.install "completions/_fish" => "disass.fish"
    test: |
      system "#{bin}/disass --version"
rigs:
  - name: disass
    rig:
      owner: blacktop
      name: fish-food
    homepage: https://github.com/blacktop/arm64-cgo
    description: MachO ARMv9-a Disassembler
    license: MIT
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge branch
release:
  footer: |
    ## What to do next?
    - Follow us on [Twitter](https://twitter.com/blacktop__);