// Code generated by "stringer -type=returnCode -output return_string.go"; DO NOT EDIT.

package disassemble

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DECODE_STATUS_ERROR_OPERANDS - -9]
	_ = x[DECODE_STATUS_ASSERT_FAILED - -8]
	_ = x[DECODE_STATUS_UNREACHABLE - -7]
	_ = x[DECODE_STATUS_LOST - -6]
	_ = x[DECODE_STATUS_END_OF_INSTRUCTION - -5]
	_ = x[DECODE_STATUS_UNDEFINED - -4]
	_ = x[DECODE_STATUS_UNALLOCATED - -3]
	_ = x[DECODE_STATUS_UNMATCHED - -2]
	_ = x[DECODE_STATUS_RESERVED - -1]
	_ = x[SUCCESS_OK-0]
	_ = x[INVALID_ARGUMENTS-1]
	_ = x[FAILED_TO_DISASSEMBLE_OPERAND-2]
	_ = x[FAILED_TO_DISASSEMBLE_OPERATION-3]
	_ = x[FAILED_TO_DISASSEMBLE_REGISTER-4]
	_ = x[FAILED_TO_DECODE_INSTRUCTION-5]
	_ = x[OUTPUT_BUFFER_TOO_SMALL-6]
	_ = x[OPERAND_IS_NOT_REGISTER-7]
	_ = x[NOT_MEMORY_OPERAND-8]
}

const _returnCode_name = "DECODE_STATUS_ERROR_OPERANDSDECODE_STATUS_ASSERT_FAILEDDECODE_STATUS_UNREACHABLEDECODE_STATUS_LOSTDECODE_STATUS_END_OF_INSTRUCTIONDECODE_STATUS_UNDEFINEDDECODE_STATUS_UNALLOCATEDDECODE_STATUS_UNMATCHEDDECODE_STATUS_RESERVEDSUCCESS_OKINVALID_ARGUMENTSFAILED_TO_DISASSEMBLE_OPERANDFAILED_TO_DISASSEMBLE_OPERATIONFAILED_TO_DISASSEMBLE_REGISTERFAILED_TO_DECODE_INSTRUCTIONOUTPUT_BUFFER_TOO_SMALLOPERAND_IS_NOT_REGISTERNOT_MEMORY_OPERAND"

var _returnCode_index = [...]uint16{0, 28, 55, 80, 98, 130, 153, 178, 201, 223, 233, 250, 279, 310, 340, 368, 391, 414, 432}

func (i returnCode) String() string {
	i -= -9
	if i < 0 || i >= returnCode(len(_returnCode_index)-1) {
		return "returnCode(" + strconv.FormatInt(int64(i+-9), 10) + ")"
	}
	return _returnCode_name[_returnCode_index[i]:_returnCode_index[i+1]]
}
